spring.application.name=globalsportsarena

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/playarena_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Configuration (Gmail SMTP)
# NOTE: Replace with your actual 16-character Google App Password (Google Account -> Security -> App Passwords)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanketshendage0750@gmail.com
spring.mail.password=oxpfdkbpsnxovjxw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Fast2SMS SMS Gateway Configuration
# Sign up at https://www.fast2sms.com/ to get your free API key
fast2sms.api.key=l80GkpFyidISaogQhLR1DVJ4AX7rmCwfHbNZqE9YUjc62tKuP59LhD1iFv4ASVtJOsykdxwmrPYQ7uM6